### ISSUE TITLE
Scripts should not need arguments and should be run by make

### ISSUE THREAD

**Issue by rufuspollock** [datasets/inflation#2]
We have an evolving best practice:
- Build scripts should be silent and not require command line arguments e.g. just run `python scripts/process.py` not `python scripts/process.py --flag argument`
- Primary script should be called `process.{ext}` e.g. `process.py`
- There should be a Makefile that runs the build (in the scripts directory) so that standard build is:
  `
  cd scripts
  make
  `

Can we try implementing this here please.

**Comment by zelima** [comment]
That's great. I was thinking the same.
The reason script is written like this is that I implemented it like script for CPI was implemented.
I'll reimplement this one. 
Do you want me to reimplement script for CPI as well?

**Comment by zelima** [comment]
@rgrp Done, please see link: https://github.com/datasets/inflation/blob/master/scripts/process.py

**Comment by rufuspollock** [comment]
What happened with makefile stuff?

**Comment by zelima** [comment]
@rgrp Can you please explain more about makefile. I'm little confused.

**Comment by rufuspollock** [comment]
@zelima are you familiar with makefiles? If not suggest a quick google and looking at example e.g. here https://github.com/datasets/global-temp

BTW based on that example i suggest:
- Makefile live in base directory
- Command to process data be called `data`

**Comment by zelima** [comment]
@rgrp please check Makefile I added. Does it fit your request? https://github.com/datasets/inflation/blob/master/Makefile

**Comment by rufuspollock** [comment]
@zelima looks great!
