### ISSUE TITLE
datapackage download link points to wrong files

### ISSUE THREAD

**Issue by zelima** [datasets/inflation#3]
@rgrp For now "resources" part  for "schema" points to the download links of original files from World Bank, **Not to the CSV files that are datapackage'd**.  
Right now data package looks [like this](http://data.okfn.org/tools/view?url=https%3A%2F%2Fgithub.com%2Fdatasets%2Finflation) - The names for data files are wrong, there are some values that are missing, for example there are no data in  "year" column. 
That's because In "Resource part" I use world bank API download link. So I'm going to change 
`"url": ''http://...."`
to 
`"path": "data/filename.csv"`

**Comment by rufuspollock** [comment]
@zelima that is correct and please correct this asap.

All resources in "core" data packages should have a `path` not `url` - the url to original dataset should be in `sources` seciton of resource (if we have it at all).

**Comment by zelima** [comment]
@rgrp fixed.
If path is must, then [CPI](http://data.okfn.org/tools/view?url=https%3A%2F%2Fgithub.com%2Fdatasets%2Fcpi) should be changed as well

**Comment by rufuspollock** [comment]
@zelima great - please open a PR on CPI then as well. Can we close this?

**Comment by zelima** [comment]
@rgrp yes, I believe everything works fine now. 
pull request is open on CPI
